#!/usr/bin/env bash
# cross-language-visibility.sh
#
# Build a cross-language visibility graph for mixed ObjC/Swift iOS projects.
# Outputs YAML describing:
#   - bridging_headers: Swift→ObjC imports via *-Bridging-Header.h
#   - generated_swift_headers: ObjC→Swift via *-Swift.h imports
#   - objc_exposed_swift: Swift symbols made ObjC-visible (@objc, @objcMembers,
#                        NS_SWIFT_NAME on the ObjC side)
#   - nullability: .h files adopting NS_ASSUME_NONNULL_BEGIN / _Nullable / _Nonnull
#
# Usage: cross-language-visibility.sh <project-root> [--output <path>]
#
set -euo pipefail

PROJECT_ROOT="${1:?Usage: cross-language-visibility.sh <project-root> [--output <path>]}"
OUTPUT=""

shift || true
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT="$2"; shift 2 ;;
        *) shift ;;
    esac
done

[[ -d "$PROJECT_ROOT" ]] || { echo "error: not a directory: $PROJECT_ROOT" >&2; exit 2; }

if [[ -z "$OUTPUT" ]]; then
    OUTPUT="$PROJECT_ROOT/.sourceatlas/cross-language.yaml"
fi
mkdir -p "$(dirname "$OUTPUT")"

# Exclude common vendor/build paths
EXCLUDE_RE='/(Pods|node_modules|\.build|DerivedData|build|Carthage|vendor)/'

# ── 1. Bridging headers ──────────────────────────────────────────────
find_bridging_headers() {
    find "$PROJECT_ROOT" -name "*-Bridging-Header.h" -type f 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" || true
}

extract_bridging_imports() {
    local bh="$1"
    grep -E '^[[:space:]]*#[[:space:]]*import[[:space:]]+["<]' "$bh" 2>/dev/null \
        | sed -E 's/^[[:space:]]*#[[:space:]]*import[[:space:]]+[<"]([^">]+)[">].*/\1/' \
        | grep -v '^$' || true
}

# ── 2. Generated -Swift.h imports (ObjC → Swift) ─────────────────────
find_swift_h_imports() {
    grep -rEn '#\s*import\s+["<][A-Za-z0-9_]+-Swift\.h[">]' \
        --include="*.m" --include="*.mm" --include="*.h" \
        "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" || true
}

# ── 3. Swift → ObjC exposed surface ──────────────────────────────────
count_objc_annotations() {
    grep -rE "^\s*$1\b" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" \
        | wc -l | tr -d ' '
}

list_objcmembers_files() {
    grep -rlE '^\s*@objcMembers\b' --include="*.swift" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" || true
}

list_ns_swift_name() {
    grep -rEn 'NS_SWIFT_NAME\([^)]+\)' --include="*.h" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" || true
}

list_ns_refined_for_swift() {
    grep -rln 'NS_REFINED_FOR_SWIFT' --include="*.h" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" || true
}

# ── 4. Nullability ───────────────────────────────────────────────────
count_nonnull_region_headers() {
    grep -rl 'NS_ASSUME_NONNULL_BEGIN' --include="*.h" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" | wc -l | tr -d ' '
}

count_nullable_tokens() {
    grep -rhE '_Nullable\b|_Nonnull\b|nullable\b|nonnull\b' \
        --include="*.h" "$PROJECT_ROOT" 2>/dev/null \
        | wc -l | tr -d ' '
}

count_all_headers() {
    find "$PROJECT_ROOT" -name "*.h" -type f 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" | wc -l | tr -d ' '
}

# ── Emit YAML ────────────────────────────────────────────────────────
{
    echo "# Cross-Language Visibility Graph"
    echo "# Generated by cross-language-visibility.sh"
    echo "project_root: \"$PROJECT_ROOT\""
    echo "generated_at: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo ""

    # Bridging headers
    echo "bridging_headers:"
    bh_count=0
    while IFS= read -r bh; do
        [[ -z "$bh" ]] && continue
        bh_count=$((bh_count + 1))
        rel="${bh#$PROJECT_ROOT/}"
        echo "  - path: \"$rel\""
        echo "    imports:"
        extract_bridging_imports "$bh" | while IFS= read -r imp; do
            echo "      - \"$imp\""
        done
    done < <(find_bridging_headers)
    echo "bridging_headers_count: $bh_count"
    echo ""

    # Generated -Swift.h (ObjC → Swift)
    echo "generated_swift_headers:"
    swift_h_count=0
    tmp_swifth=$(mktemp)
    find_swift_h_imports > "$tmp_swifth"
    swift_h_count=$(wc -l < "$tmp_swifth" | tr -d ' ')
    # Group by importing file
    awk -F: '{print $1}' "$tmp_swifth" | sort -u | while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        rel="${f#$PROJECT_ROOT/}"
        echo "  - importer: \"$rel\""
    done
    rm -f "$tmp_swifth"
    echo "generated_swift_headers_count: $swift_h_count"
    echo ""

    # Swift → ObjC exposed surface
    echo "objc_exposed_swift:"
    objc_count=$(count_objc_annotations '@objc')
    objcmem_count=$(count_objc_annotations '@objcMembers')
    echo "  objc_annotations: $objc_count"
    echo "  objcmembers_annotations: $objcmem_count"
    echo "  objcmembers_files:"
    list_objcmembers_files | while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        rel="${f#$PROJECT_ROOT/}"
        echo "    - \"$rel\""
    done
    ns_swift_name_count=$(list_ns_swift_name | wc -l | tr -d ' ')
    ns_refined_count=$(list_ns_refined_for_swift | wc -l | tr -d ' ')
    echo "  ns_swift_name_count: $ns_swift_name_count"
    echo "  ns_refined_for_swift_files: $ns_refined_count"
    echo ""

    # Nullability
    echo "nullability:"
    total_h=$(count_all_headers)
    nonnull_h=$(count_nonnull_region_headers)
    tokens=$(count_nullable_tokens)
    echo "  total_headers: $total_h"
    echo "  headers_with_nonnull_region: $nonnull_h"
    if [[ "$total_h" -gt 0 ]]; then
        pct=$(( nonnull_h * 100 / total_h ))
        echo "  nonnull_coverage_pct: $pct"
    else
        echo "  nonnull_coverage_pct: 0"
    fi
    echo "  nullability_token_count: $tokens"
    echo ""

    echo "summary:"
    echo "  language_boundaries: $((bh_count + swift_h_count))"
    echo "  swift_to_objc_exposure: $((objc_count + objcmem_count + ns_swift_name_count))"
    echo "  objc_to_swift_safety: $nonnull_h"
} > "$OUTPUT"

echo "wrote $OUTPUT"
