#!/usr/bin/env bash
# init-step2a.sh — Step 2a Zone Discovery: deterministic zone detection.
#
# Reads state.yaml to find the target file, runs detect-zones.sh, picks a
# first-slice zone via deterministic ranking, writes 2a_zones.yaml, and
# advances state via state.sh.
#
# Usage:
#   init-step2a.sh <project-root> --module <name> [--force]
#
# Requires: state.yaml exists at .sourceatlas/refactor/{module}/state.yaml
#           with steps.1_target.status in {produced, verified}.
#
# Exit codes:
#   0  success — 2a_zones.yaml written, state advanced
#   1  usage error
#   2  state.yaml not found / Step 1 not done
#   3  2a_zones.yaml already exists and --force not given
#   4  detect-zones.sh failed
#
set -euo pipefail

PROJECT_ROOT="${1:?Usage: init-step2a.sh <project-root> --module <name> [--force]}"
shift

MODULE=""
FORCE=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --module) MODULE="$2"; shift 2 ;;
        --force)  FORCE=1;     shift   ;;
        *)        shift                ;;
    esac
done
[[ -n "$MODULE" ]] || { echo "error: --module required" >&2; exit 1; }

PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

state_dir="$PROJECT_ROOT/.sourceatlas/refactor/$MODULE"
state_file="$state_dir/state.yaml"
zones_file="$state_dir/2a_zones.yaml"

[[ -f "$state_file" ]] || { echo "error: state.yaml not found at $state_file" >&2; exit 2; }

if [[ -f "$zones_file" && "$FORCE" -ne 1 ]]; then
    echo "error: $zones_file already exists. Re-run with --force to overwrite." >&2
    exit 3
fi

# Read target file path + language from state.yaml
target_rel=$(awk -F'"' '/^file:/ {print $2; exit}' "$state_file")
language=$(awk -F'"' '/^language:/ {print $2; exit}' "$state_file")
[[ -n "$target_rel" ]] || { echo "error: cannot read 'file' from state.yaml" >&2; exit 2; }

target_abs="$PROJECT_ROOT/$target_rel"
[[ -f "$target_abs" ]] || { echo "error: target not found: $target_abs" >&2; exit 2; }

# Verify Step 1 is done
prev_status=$(grep -E "^[[:space:]]+1_target:" "$state_file" | sed -E 's/.*status: *([a-z]+).*/\1/')
if [[ "$prev_status" != "produced" && "$prev_status" != "verified" ]]; then
    echo "error: Step 1 not done (1_target.status=$prev_status). Run init-state.sh first." >&2
    exit 2
fi

# ── Run detect-zones.sh, capture YAML ───────────────────────────────────────
DETECT="$SCRIPT_DIR/detect-zones.sh"
[[ -f "$DETECT" ]] || DETECT="$SCRIPT_DIR/../../../scripts/atlas/detect-zones.sh"

raw_zones=$(bash "$DETECT" "$target_abs" --language "$language" 2>&1) || {
    echo "error: detect-zones.sh failed:" >&2
    echo "$raw_zones" >&2
    exit 4
}

# ── Pick first-slice zone via deterministic ranking ─────────────────────────
# Strategy: smallest line_count first; tie-break by fewest deps.
# (Phase 2 high-deps preference handled by pilot-run.sh's recommended_zone;
#  init-step2a.sh respects pilot's choice if present in pilot report, else
#  falls back to size+deps heuristic.)

pilot_report="$PROJECT_ROOT/.sourceatlas/refactor/pilot-${MODULE}.md"
recommended_zone_id=""
recommended_reason=""

if [[ -f "$pilot_report" ]]; then
    pz=$(awk '
        /^recommended_zone:/ { in_rz = 1; next }
        in_rz && /^[a-zA-Z]/  { exit }
        in_rz && /^[[:space:]]+id:/ {
            sub(/.*id:[[:space:]]*"?/, "")
            sub(/"?[[:space:]]*$/, "")
            print
            exit
        }
    ' "$pilot_report")
    if [[ -n "$pz" ]]; then
        recommended_zone_id="$pz"
        recommended_reason="from pilot report (matches phase heuristic)"
    fi
fi

if [[ -z "$recommended_zone_id" ]]; then
    # Fallback: parse raw_zones, pick smallest line_count.
    recommended_zone_id=$(echo "$raw_zones" | awk '
        /^  - id:/ {
            sub(/.*id:[[:space:]]*"?/, "")
            sub(/"?[[:space:]]*$/, "")
            id = $0
        }
        /^    line_count:/ {
            split($0, a, ":")
            lc = a[2] + 0
            if (best_lc == 0 || lc < best_lc) {
                best_lc = lc
                best_id = id
            }
        }
        END { print best_id }
    ')
    recommended_reason="smallest line_count (deterministic fallback)"
fi

[[ -n "$recommended_zone_id" ]] || { echo "error: detect-zones produced no zones" >&2; exit 4; }

# ── Write 2a_zones.yaml ─────────────────────────────────────────────────────
mkdir -p "$state_dir"
{
    echo "# Generated by init-step2a.sh"
    echo "module: \"$MODULE\""
    # detect-zones output already contains file/language/total_lines/zones
    echo "$raw_zones" | grep -vE '^# |^$'
    echo
    echo "recommended:"
    echo "  zone_id: \"$recommended_zone_id\""
    echo "  reason: \"$recommended_reason\""
} > "$zones_file"

# ── Update state via state.sh (deterministic write API) ─────────────────────
STATE_SH="$SCRIPT_DIR/state.sh"
PROJECT_ROOT="$PROJECT_ROOT" bash "$STATE_SH" set-status --module "$MODULE" --step 2a_zones --status produced >/dev/null
PROJECT_ROOT="$PROJECT_ROOT" bash "$STATE_SH" set-zone --module "$MODULE" --zone "$recommended_zone_id" >/dev/null
# Advance current_step from 1 → 2 (entering Step 2 family)
current=$(awk '/^current_step:/ {print $2; exit}' "$state_file")
if [[ "$current" == "1" ]]; then
    PROJECT_ROOT="$PROJECT_ROOT" bash "$STATE_SH" advance --module "$MODULE" --to 2 >/dev/null
fi

# ── Summary ─────────────────────────────────────────────────────────────────
zone_count=$(echo "$raw_zones" | grep -cE '^  - id:')
cat <<EOF
Step 2a — Zone Discovery: produced

  module:           $MODULE
  zones_found:      $zone_count
  recommended_zone: $recommended_zone_id
  reason:           $recommended_reason

  artifacts: $zones_file
EOF
