#!/usr/bin/env bash
# runtime-hidden-deps.sh
#
# Scan runtime-hidden dependencies that static import analysis misses but
# which are load-bearing at execution time. Critical for ObjC→Swift migration:
# if ignored, refactor plans look clean but crash in production.
#
# Emits YAML covering:
#   1. Categories (@interface X (Cat)) + Swift extensions
#   2. Method swizzling (method_exchangeImplementations / class_replaceMethod)
#   3. String-based dispatch (NSClassFromString / NSSelectorFromString /
#                             performSelector / respondsToSelector)
#   4. KVC/KVO + Notifications
#   5. Interface Builder wiring (IBOutlet / IBAction / storyboard / nib)
#
# Usage:
#   runtime-hidden-deps.sh <project-root> [--output <path>] [--target <file>]
#
# --target scopes the scan to dependencies involving that specific file
# (by file basename). Omit for a project-wide overview.
#
set -euo pipefail

PROJECT_ROOT="${1:?Usage: runtime-hidden-deps.sh <project-root> [--output <path>] [--target <file>]}"
OUTPUT=""
TARGET=""

shift || true
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT="$2"; shift 2 ;;
        --target) TARGET="$2"; shift 2 ;;
        *) shift ;;
    esac
done

[[ -d "$PROJECT_ROOT" ]] || { echo "error: not a directory: $PROJECT_ROOT" >&2; exit 2; }

if [[ -z "$OUTPUT" ]]; then
    OUTPUT="$PROJECT_ROOT/.sourceatlas/runtime-hidden-deps.yaml"
fi
mkdir -p "$(dirname "$OUTPUT")"

EXCLUDE_RE='/(Pods|node_modules|\.build|DerivedData|build|Carthage|vendor)/'
INCLUDES=(--include="*.m" --include="*.mm" --include="*.h" --include="*.swift")

# Count + list helpers
count_re() {
    local pattern="$1"
    grep -rnE "$pattern" "${INCLUDES[@]}" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" \
        | wc -l | tr -d ' '
}

list_sites() {
    local pattern="$1"
    local limit="${2:-20}"
    # Disable pipefail: head closes pipe early (SIGPIPE on grep) by design.
    set +o pipefail
    grep -rnE "$pattern" "${INCLUDES[@]}" "$PROJECT_ROOT" 2>/dev/null \
        | grep -Ev "$EXCLUDE_RE" \
        | head -"$limit" || true
    set -o pipefail
}

emit_sites_yaml() {
    local header="$1"; shift
    local pattern="$1"; shift
    local limit="${1:-20}"
    echo "  $header:"
    local tmp=$(mktemp)
    list_sites "$pattern" "$limit" > "$tmp"
    if [[ ! -s "$tmp" ]]; then
        echo "    # none"
    else
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            # format: path:line:content  → we only emit path:line
            local path_line
            path_line=$(echo "$line" | awk -F: '{print $1":"$2}')
            local rel="${path_line#$PROJECT_ROOT/}"
            echo "    - \"$rel\""
        done < "$tmp"
    fi
    rm -f "$tmp"
}

# ── Emit YAML ────────────────────────────────────────────────────────
{
    echo "# Runtime-Hidden Dependency Scan"
    echo "# Generated by runtime-hidden-deps.sh"
    echo "project_root: \"$PROJECT_ROOT\""
    echo "generated_at: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    [[ -n "$TARGET" ]] && echo "target: \"$TARGET\""
    echo ""

    # 1. Categories + Swift extensions ─ the "hidden attach points"
    echo "categories_and_extensions:"
    objc_cat=$(count_re '^@interface [A-Za-z_][A-Za-z0-9_]* \(')
    swift_ext=$(count_re '^extension [A-Z]')
    echo "  objc_category_files: $objc_cat"
    echo "  swift_extension_files: $swift_ext"
    echo "  risk_note: \"Categories add methods to classes you don't own; migration must verify each @interface (Cat) conformer still exists in target language.\""
    emit_sites_yaml "objc_category_sample_sites" '^@interface [A-Za-z_][A-Za-z0-9_]* \(' 30
    echo ""

    # 2. Method swizzling
    echo "method_swizzling:"
    swizzle_count=$(count_re 'method_exchangeImplementations|class_replaceMethod|class_getInstanceMethod|method_setImplementation')
    echo "  total_sites: $swizzle_count"
    echo "  risk_note: \"Swizzling silently mutates behavior; any refactor that changes method dispatch order can produce crashes or silent wrong answers.\""
    emit_sites_yaml "sample_sites" 'method_exchangeImplementations|class_replaceMethod|method_setImplementation' 50
    echo ""

    # 3. String-based dispatch
    echo "string_based_dispatch:"
    nsclass=$(count_re 'NSClassFromString\(')
    nsselector=$(count_re 'NSSelectorFromString\(|sel_registerName\(')
    perform=$(count_re 'performSelector[:@(]|perform\(#selector')
    responds=$(count_re 'respondsToSelector:|responds\(to:')
    echo "  ns_class_from_string: $nsclass"
    echo "  ns_selector_from_string: $nsselector"
    echo "  perform_selector: $perform"
    echo "  responds_to_selector: $responds"
    echo "  risk_note: \"String-based dispatch survives grep for the symbol name but the target is invisible to rename refactors; every match is a migration audit point.\""
    emit_sites_yaml "ns_class_from_string_sites" 'NSClassFromString\(' 30
    emit_sites_yaml "ns_selector_from_string_sites" 'NSSelectorFromString\(' 30
    echo ""

    # 4. KVC / KVO / Notification
    echo "kvc_kvo_notifications:"
    kvc=$(count_re 'valueForKey:|setValue:forKey:|valueForKeyPath:|setValue:forKeyPath:')
    kvo=$(count_re 'addObserver:forKeyPath:|removeObserver:forKeyPath:|observeValueForKeyPath:')
    notif_post=$(count_re 'postNotificationName:|NotificationCenter\.default\.post\(|NotificationCenter\.(default|shared)\.post')
    notif_observe=$(count_re 'addObserver:selector:name:|NotificationCenter\.(default|shared)\.addObserver')
    echo "  kvc_access_sites: $kvc"
    echo "  kvo_observer_sites: $kvo"
    echo "  notification_post_sites: $notif_post"
    echo "  notification_observer_sites: $notif_observe"
    echo "  risk_note: \"KVC/KVO keypaths and notification names are strings; renames and type migrations break them silently. Swift #keyPath() helps only after migration.\""
    emit_sites_yaml "kvo_sample_sites" 'addObserver:forKeyPath:|observeValueForKeyPath:' 30
    emit_sites_yaml "notification_post_sample_sites" 'postNotificationName:' 30
    echo ""

    # 5. IB wiring
    echo "interface_builder:"
    ib_outlet=$(count_re 'IBOutlet|@IBOutlet')
    ib_action=$(count_re 'IBAction|@IBAction')
    storyboard=$(count_re 'instantiateViewControllerWithIdentifier:|instantiateViewController\(withIdentifier:|UIStoryboard\(name:')
    nib_nib=$(count_re 'UINib\(nibName:|nibWithNibName:|loadNibNamed:')
    reuse_id=$(count_re 'dequeueReusableCellWithIdentifier:|dequeueReusableCell\(withIdentifier:|registerClass:forCellReuseIdentifier:|registerClass:forCellWithReuseIdentifier:|register\(.*forCellReuseIdentifier:')
    echo "  ibooutlets: $ib_outlet"
    echo "  ibactions: $ib_action"
    echo "  storyboard_instantiations: $storyboard"
    echo "  nib_loads: $nib_nib"
    echo "  reuse_identifier_sites: $reuse_id"
    echo "  risk_note: \"Class names, outlet names, segue IDs and reuse IDs are strings in .storyboard/.xib and crash on mismatch at runtime. Refactor must update XML alongside code.\""
    emit_sites_yaml "storyboard_instantiation_sites" 'instantiateViewControllerWithIdentifier:|instantiateViewController\(withIdentifier:' 30
    echo ""

    # ── Summary
    echo "summary:"
    total_hidden=$((objc_cat + swift_ext + swizzle_count + nsclass + nsselector + perform + kvo + notif_post + ib_outlet + storyboard))
    echo "  total_hidden_surface_sites: $total_hidden"
    echo "  showstoppers:"
    [[ $swizzle_count -gt 0 ]] && echo "    - \"swizzle($swizzle_count): method dispatch mutation — any migration must preserve order\""
    [[ $((nsclass + nsselector)) -gt 10 ]] && echo "    - \"string-dispatch($((nsclass + nsselector))): symbol-rename refactors will break these\""
    [[ $kvo -gt 50 ]] && echo "    - \"kvo($kvo): keypath strings survive rename refactors silently\""
    [[ $storyboard -gt 0 ]] && echo "    - \"storyboard($storyboard): class name strings in XML\""
    [[ $objc_cat -gt 100 ]] && echo "    - \"categories($objc_cat): each is a method-injection surface; migration must re-verify conformance\""
} > "$OUTPUT"

echo "wrote $OUTPUT"
